## Example 1

![https://www.linkedin.com/in/nidhalselmi/](https://raw.githubusercontent.com/Nydhal/Python-Notebooks/master/images/Bayes_Network.png "If you use this code shout out to @imleslahdin on twitter")

In [1]:
#!pip install pgmpy
#!conda install -c ankurankan pgmpy
from pgmpy.models import BayesianModel as bayes
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import VariableElimination
import itertools as it
import pandas as pd

#Define model structure. We define the network by passing a list of edges.
model = bayes([('T','A'),('F','A'),('F','S'),('A','L'),('L','R')])

#Define Conditional Probability Desntiy Tables
cpd_T = TabularCPD(variable='T', variable_card=2, values=[[.9, .1]])
cpd_F = TabularCPD(variable='F', variable_card=2, values=[[.9999, .0001]])
cpd_S=TabularCPD('S',2,[[.9,.1],[.1,.9]],['F'],[2])
cpd_A=TabularCPD('A',2,[[.9999,.01,.15,.5],[.0001,.99,.85,.5]],['F','T'],[2,2])
cpd_L=TabularCPD('L',2,[[.999,.12],[.001,.88]],['A'],[2])
cpd_R=TabularCPD('R',2,[[.99,.25],[.01,.75]],['L'],[2])

#Adding the CPDs to the network
model.add_cpds(cpd_T,cpd_F,cpd_S,cpd_A,cpd_L,cpd_R)

#Check the network structure and verify the CPDs.
print('Model Check:',model.check_model())

#Print all CPDs
print('All the Conditional Probability Distribution Tables of our model:')
for cpd in model.get_cpds():
    print(cpd)

# Getting all the local independencies in the network.
print('\n Local independencies:')
print(model.local_independencies(['T', 'F', 'S', 'L', 'A','R']))

#Infer using variable elimination algorithm
infer = VariableElimination(model)
print('\n Query A:')
print(infer.query(['A']) ['A'])

#Inference with evidence
print('\n Inference on A with evidence S=1, R=1:')
print(infer.query(['A'], evidence={'S': 1, 'R': 1}) ['A'])
print('\n Inference on A with evidence S=1, R=0:')
print(infer.query(['A'], evidence={'S': 1, 'R': 0}) ['A'])
print('\n Inference on A with evidence S=0, R=1:')
print(infer.query(['A'], evidence={'S': 0, 'R': 1}) ['A'])
print('\n Inference on A with evidence S=0, R=0:')
print(infer.query(['A'], evidence={'S': 0, 'R': 0}) ['A'])

('Model Check:', True)
All the Conditional Probability Distribution Tables of our model:
+-----+-----+
| T_0 | 0.9 |
+-----+-----+
| T_1 | 0.1 |
+-----+-----+
+-----+--------+
| F_0 | 0.9999 |
+-----+--------+
| F_1 | 0.0001 |
+-----+--------+
+-----+-----+-----+
| F   | F_0 | F_1 |
+-----+-----+-----+
| S_0 | 0.9 | 0.1 |
+-----+-----+-----+
| S_1 | 0.1 | 0.9 |
+-----+-----+-----+
+-----+--------+------+------+-----+
| F   | F_0    | F_0  | F_1  | F_1 |
+-----+--------+------+------+-----+
| T   | T_0    | T_1  | T_0  | T_1 |
+-----+--------+------+------+-----+
| A_0 | 0.9999 | 0.01 | 0.15 | 0.5 |
+-----+--------+------+------+-----+
| A_1 | 0.0001 | 0.99 | 0.85 | 0.5 |
+-----+--------+------+------+-----+
+-----+-------+------+
| A   | A_0   | A_1  |
+-----+-------+------+
| L_0 | 0.999 | 0.12 |
+-----+-------+------+
| L_1 | 0.001 | 0.88 |
+-----+-------+------+
+-----+------+------+
| L   | L_0  | L_1  |
+-----+------+------+
| R_0 | 0.99 | 0.25 |
+-----+------+------+
| R_1 | 0.01 | 0.75 |
+-----+------+------+

 Local independencies:
(T _|_ S, F)
(F _|_ T)
(S _|_ A, R, L, T | F)
(L _|_ S, T, F | A)
(A _|_ S | T, F)
(R _|_ A, S, T, F | L)

 Query A:
+-----+----------+
| A   |   phi(A) |
+=====+==========+
| A_0 |   0.9008 |
+-----+----------+
| A_1 |   0.0992 |
+-----+----------+

 Inference on A with evidence S=1, R=1:
+-----+----------+
| A   |   phi(A) |
+=====+==========+
| A_0 |   0.1279 |
+-----+----------+
| A_1 |   0.8721 |
+-----+----------+

 Inference on A with evidence S=1, R=0:
+-----+----------+
| A   |   phi(A) |
+=====+==========+
| A_0 |   0.9634 |
+-----+----------+
| A_1 |   0.0366 |
+-----+----------+

 Inference on A with evidence S=0, R=1:
+-----+----------+
| A   |   phi(A) |
+=====+==========+
| A_0 |   0.1287 |
+-----+----------+
| A_1 |   0.8713 |
+-----+----------+

 Inference on A with evidence S=0, R=0:
+-----+----------+
| A   |   phi(A) |
+=====+==========+
| A_0 |   0.9637 |
+-----+----------+
| A_1 |   0.0363 |
+-----+----------+

## Example 2

![https://www.linkedin.com/in/nidhalselmi/](https://raw.githubusercontent.com/Nydhal/Python-Notebooks/master/images/Bayes_Network_2.png "If you use this code shout out to @imleslahdin on twitter")

 If we want to randomly initialize the probabilities,
 
 we can use either uniform random \[0,1) sample or a flat Drichlet distribution.

In [17]:
p = np.random.random()
q = 1-p
print([p,q])
print(np.random.dirichlet(np.ones(3),size=1))
print(np.random.dirichlet(np.ones(4),size=1))

[0.07063387551513245, 0.9293661244848676]
[[0.54661688 0.30133316 0.15204996]]
[[0.07603153 0.15746865 0.33391534 0.43258448]]

In [21]:
# Load CPD tables
df1 = pd.DataFrame({'P(d1|abc)':[0.428,0.818,0.142,0.857,0.875,0.181,000.5,0.384,0.166,0.111,000.5,0.222,0.181,0.642,00.75,0.583],'P(d2|abc)':[0.572,0.182,0.858,0.143,0.125,0.819,0.5,0.616,0.834,0.889,0.5,0.778,0.819,0.358,0.25,0.417]})
df2 = pd.DataFrame({'P(e1|abc)':[0.818,0.857,0.181,0.384,0.111,0.222,0.642,0.583,000.5,0.454,000.5,000.2,0.692,0.437,0.428,000.4],'P(e2|abc)':[0.182,0.143,0.819,0.616,0.889,0.778,0.358,0.417,0.5,0.546,0.5,0.8,0.308,0.563,0.572,0.6]})
df3 = pd.DataFrame({'P(g1|de)':[0.066,0.142,0.546,0.375],'P(g2|de)':[0.140,0.714,0.152,0.375],'P(g3|de)':[0.794,0.144,0.301,0.25]})
df4 = pd.DataFrame({'P(h1|de)':[0.142,0.375,0.357,000.4],'P(h2|de)':[0.714,0.375,0.357,0.066],'P(h3|de)':[0.144,0.25,0.286,0.534]})
df5 = pd.DataFrame({'P(f1|de)':[0.117,00.36,0.076,0.333],'P(f2|de)':[0.280,00.16,0.333,0.416],'P(f3|de)':[0.588,00.36,0.157,00.25],'P(f4|de)':[0.013,0.12,0.432,0.001]})

de  = pd.concat([df3, df4, df5], axis=1, join_axes=[df3.index])
de.index = [i for i in it.product(['d1','d2'],['e1','e2'])]
display(de)

abc = pd.concat([df1, df2], axis=1, join_axes=[df1.index])
abc.index = [i for i in it.product(['a1','a2'],['b1','b2','b3','b4'],['c1','c2'])]
display(abc)

,P(g1|de),P(g2|de),P(g3|de),P(h1|de),P(h2|de),P(h3|de),P(f1|de),P(f2|de),P(f3|de),P(f4|de)
"(d1, e1)",0.066,0.140,0.794,0.142,0.714,0.144,0.117,0.280,0.588,0.013
"(d1, e2)",0.142,0.714,0.144,0.375,0.375,0.250,0.360,0.160,0.360,0.120
"(d2, e1)",0.546,0.152,0.301,0.357,0.357,0.286,0.076,0.333,0.157,0.432
"(d2, e2)",0.375,0.375,0.250,0.400,0.066,0.534,0.333,0.416,0.250,0.001

              P(d1|abc)  P(d2|abc)  P(e1|abc)  P(e2|abc)
(a1, b1, c1)      0.428      0.572      0.818      0.182
(a1, b1, c2)      0.818      0.182      0.857      0.143
(a1, b2, c1)      0.142      0.858      0.181      0.819
(a1, b2, c2)      0.857      0.143      0.384      0.616
(a1, b3, c1)      0.875      0.125      0.111      0.889
(a1, b3, c2)      0.181      0.819      0.222      0.778
(a1, b4, c1)      0.500      0.500      0.642      0.358
(a1, b4, c2)      0.384      0.616      0.583      0.417
(a2, b1, c1)      0.166      0.834      0.500      0.500
(a2, b1, c2)      0.111      0.889      0.454      0.546
(a2, b2, c1)      0.500      0.500      0.500      0.500
(a2, b2, c2)      0.222      0.778      0.200      0.800
(a2, b3, c1)      0.181      0.819      0.692      0.308
(a2, b3, c2)      0.642      0.358      0.437      0.563
(a2, b4, c1)      0.750      0.250      0.428      0.572
(a2, b4, c2)      0.583      0.417      0.400      0.600

In [22]:
#Define model structure. We define the network by passing a list of edges.
model = bayes([('A','D'),('A','E'),
               ('B','D'),('B','E'),
               ('C','D'),('C','E'),
               ('D','F'),('D','G'),('D','H'),
               ('E','F'),('E','G'),('E','H')])

Family_History = TabularCPD(variable='A', variable_card=2, values=[[.6, .4]])
Asbestos_Exposure = TabularCPD(variable='B', variable_card=4, values=[[.1, .6, .2, .1]])
Smoking = TabularCPD(variable='C', variable_card=2, values=[[.3, .7]])

Asthma =TabularCPD('D',2,
                   [list(abc['P(d1|abc)']),
                    list(abc['P(d2|abc)'])],
                   ['A','B','C'],[2,4,2])

Lung_Cancer =TabularCPD('E',2,
                        [list(abc['P(e1|abc)']),
                         list(abc['P(e2|abc)'])],
                        ['A','B','C'],[2,4,2])

Breathing_Trouble =TabularCPD('G',3,
                              [list(de['P(g1|de)']),
                               list(de['P(g2|de)']),
                               list(de['P(g3|de)'])],
                              ['D','E'],[2,2])

Chest_Pain =TabularCPD('H',3,
                     [list(de['P(h1|de)']),
                      list(de['P(h2|de)']),
                      list(de['P(h3|de)'])],
                     ['D','E'],[2,2])

Wheezing =TabularCPD('F',4,
                       [list(de['P(f1|de)']),
                        list(de['P(f2|de)']),
                        list(de['P(f3|de)']),
                        list(de['P(f4|de)'])],
                       ['D','E'],[2,2])

#Adding the CPDs to the network
model.add_cpds(Family_History,Asbestos_Exposure,Smoking,
               Asthma,
               Lung_Cancer,
               Breathing_Trouble,
               Wheezing,
               Chest_Pain)

#Check the network structure and verify the CPDs.
print('Model Check:',model.check_model())

#Print all CPDs
print('All the Conditional Probability Distribution Tables of our model:')
for cpd in model.get_cpds():
    print(cpd)

#Infer using variable elimination algorithm
infer = VariableElimination(model)

('Model Check:', True)
All the Conditional Probability Distribution Tables of our model:
+-----+-----+
| A_0 | 0.6 |
+-----+-----+
| A_1 | 0.4 |
+-----+-----+
+-----+-----+
| B_0 | 0.1 |
+-----+-----+
| B_1 | 0.6 |
+-----+-----+
| B_2 | 0.2 |
+-----+-----+
| B_3 | 0.1 |
+-----+-----+
+-----+-----+
| C_0 | 0.3 |
+-----+-----+
| C_1 | 0.7 |
+-----+-----+
+-----+-------+-------+-------+-------+-------+-------+-----+-------+-------+-------+-----+-------+-------+-------+------+-------+
| A   | A_0   | A_0   | A_0   | A_0   | A_0   | A_0   | A_0 | A_0   | A_1   | A_1   | A_1 | A_1   | A_1   | A_1   | A_1  | A_1   |
+-----+-------+-------+-------+-------+-------+-------+-----+-------+-------+-------+-----+-------+-------+-------+------+-------+
| B   | B_0   | B_0   | B_1   | B_1   | B_2   | B_2   | B_3 | B_3   | B_0   | B_0   | B_1 | B_1   | B_2   | B_2   | B_3  | B_3   |
+-----+-------+-------+-------+-------+-------+-------+-----+-------+-------+-------+-----+-------+-------+-------+------+-------+
| C   | C_0   | C_1   | C_0   | C_1   | C_0   | C_1   | C_0 | C_1   | C_0   | C_1   | C_0 | C_1   | C_0   | C_1   | C_0  | C_1   |
+-----+-------+-------+-------+-------+-------+-------+-----+-------+-------+-------+-----+-------+-------+-------+------+-------+
| D_0 | 0.428 | 0.818 | 0.142 | 0.857 | 0.875 | 0.181 | 0.5 | 0.384 | 0.166 | 0.111 | 0.5 | 0.222 | 0.181 | 0.642 | 0.75 | 0.583 |
+-----+-------+-------+-------+-------+-------+-------+-----+-------+-------+-------+-----+-------+-------+-------+------+-------+
| D_1 | 0.572 | 0.182 | 0.858 | 0.143 | 0.125 | 0.819 | 0.5 | 0.616 | 0.834 | 0.889 | 0.5 | 0.778 | 0.819 | 0.358 | 0.25 | 0.417 |
+-----+-------+-------+-------+-------+-------+-------+-----+-------+-------+-------+-----+-------+-------+-------+------+-------+
+-----+-------+-------+-------+-------+-------+-------+-------+-------+-----+-------+-----+-----+-------+-------+-------+-----+
| A   | A_0   | A_0   | A_0   | A_0   | A_0   | A_0   | A_0   | A_0   | A_1 | A_1   | A_1 | A_1 | A_1   | A_1   | A_1   | A_1 |
+-----+-------+-------+-------+-------+-------+-------+-------+-------+-----+-------+-----+-----+-------+-------+-------+-----+
| B   | B_0   | B_0   | B_1   | B_1   | B_2   | B_2   | B_3   | B_3   | B_0 | B_0   | B_1 | B_1 | B_2   | B_2   | B_3   | B_3 |
+-----+-------+-------+-------+-------+-------+-------+-------+-------+-----+-------+-----+-----+-------+-------+-------+-----+
| C   | C_0   | C_1   | C_0   | C_1   | C_0   | C_1   | C_0   | C_1   | C_0 | C_1   | C_0 | C_1 | C_0   | C_1   | C_0   | C_1 |
+-----+-------+-------+-------+-------+-------+-------+-------+-------+-----+-------+-----+-----+-------+-------+-------+-----+
| E_0 | 0.818 | 0.857 | 0.181 | 0.384 | 0.111 | 0.222 | 0.642 | 0.583 | 0.5 | 0.454 | 0.5 | 0.2 | 0.692 | 0.437 | 0.428 | 0.4 |
+-----+-------+-------+-------+-------+-------+-------+-------+-------+-----+-------+-----+-----+-------+-------+-------+-----+
| E_1 | 0.182 | 0.143 | 0.819 | 0.616 | 0.889 | 0.778 | 0.358 | 0.417 | 0.5 | 0.546 | 0.5 | 0.8 | 0.308 | 0.563 | 0.572 | 0.6 |
+-----+-------+-------+-------+-------+-------+-------+-------+-------+-----+-------+-----+-----+-------+-------+-------+-----+
+-----+-------+-------+-------+-------+
| D   | D_0   | D_0   | D_1   | D_1   |
+-----+-------+-------+-------+-------+
| E   | E_0   | E_1   | E_0   | E_1   |
+-----+-------+-------+-------+-------+
| G_0 | 0.066 | 0.142 | 0.546 | 0.375 |
+-----+-------+-------+-------+-------+
| G_1 | 0.14  | 0.714 | 0.152 | 0.375 |
+-----+-------+-------+-------+-------+
| G_2 | 0.794 | 0.144 | 0.301 | 0.25  |
+-----+-------+-------+-------+-------+
+-----+-------+------+-------+-------+
| D   | D_0   | D_0  | D_1   | D_1   |
+-----+-------+------+-------+-------+
| E   | E_0   | E_1  | E_0   | E_1   |
+-----+-------+------+-------+-------+
| F_0 | 0.117 | 0.36 | 0.076 | 0.333 |
+-----+-------+------+-------+-------+
| F_1 | 0.28  | 0.16 | 0.333 | 0.416 |
+-----+-------+------+-------+-------+
| F_2 | 0.588 | 0.36 | 0.157 | 0.25  |
+-----+-------+------+-------+-------+
| F_3 | 0.013 | 0.12 | 0.432 | 0.001 |
+-----+-------+------+-------+-------+
+-----+-------+-------+-------+-------+
| D   | D_0   | D_0   | D_1   | D_1   |
+-----+-------+-------+-------+-------+
| E   | E_0   | E_1   | E_0   | E_1   |
+-----+-------+-------+-------+-------+
| H_0 | 0.142 | 0.375 | 0.357 | 0.4   |
+-----+-------+-------+-------+-------+
| H_1 | 0.714 | 0.375 | 0.357 | 0.066 |
+-----+-------+-------+-------+-------+
| H_2 | 0.144 | 0.25  | 0.286 | 0.534 |
+-----+-------+-------+-------+-------+

![https://www.linkedin.com/in/nidhalselmi/](https://raw.githubusercontent.com/Nydhal/Python-Notebooks/master/images/Bayes_Net_3.png "If you use this code shout out to @imleslahdin on twitter")

In [20]:
print(infer.query(['E'], evidence={'C':0, 'H':1, 'G':2, 'B':1}) ['E'])
print(infer.query(['D'], evidence={'C':0, 'G':1, 'B':3}) ['D'])

+-----+----------+
| E   |   phi(E) |
+=====+==========+
| E_0 |   0.7962 |
+-----+----------+
| E_1 |   0.2038 |
+-----+----------+
+-----+----------+
| D   |   phi(D) |
+=====+==========+
| D_0 |   0.5864 |
+-----+----------+
| D_1 |   0.4136 |
+-----+----------+